//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.21 at 12:23:44 AM GST 
//


package com.liconic.binding.sys;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Contains an information about pending or active command.
 * All tags taken from STXCommand and STXAnswer.
 * 
 * <p>Java class for STXCmdStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STXCmdStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Cmd">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="GetCmdStatus"/>
 *               &lt;enumeration value="GetSTXInfo"/>
 *               &lt;enumeration value="GetPlateInfo"/>
 *               &lt;enumeration value="GetTubeInfo"/>
 *               &lt;enumeration value="StorePlate"/>
 *               &lt;enumeration value="RetrievePlate"/>
 *               &lt;enumeration value="PickTubes"/>
 *               &lt;enumeration value="Inventory"/>
 *               &lt;enumeration value="ReadyForStorePlate"/>
 *               &lt;enumeration value="ReadyForRetrievePlate"/>
 *               &lt;enumeration value="AbortCmd"/>
 *               &lt;enumeration value="Activate"/>
 *               &lt;enumeration value="Deactivate"/>
 *               &lt;enumeration value="GetDeviceStatus"/>
 *               &lt;enumeration value="GetSystemStatus"/>
 *               &lt;enumeration value="GetCommandsInfo"/>
 *               &lt;enumeration value="GetPartitionPlatesList"/>
 *               &lt;enumeration value="GetPartitionTubesList"/>
 *               &lt;enumeration value="Consolidate"/>
 *               &lt;enumeration value="MoveTubes"/>
 *               &lt;enumeration value="GetUpdateMessage"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="User" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="OK"/>
 *               &lt;enumeration value="DONE"/>
 *               &lt;enumeration value="RUN"/>
 *               &lt;enumeration value="ERR"/>
 *               &lt;enumeration value="ABORTED"/>
 *               &lt;enumeration value="WAIT"/>
 *               &lt;enumeration value="BREAK"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ErrCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ErrMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Progress" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STXCmdStatus", propOrder = {
    "id",
    "cmd",
    "user",
    "status",
    "errCode",
    "errMsg",
    "progress"
})
public class STXCmdStatus {

    @XmlElement(name = "ID")
    protected int id;
    @XmlElement(name = "Cmd", required = true)
    protected String cmd;
    @XmlElement(name = "User", required = true)
    protected String user;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "ErrCode")
    protected int errCode;
    @XmlElement(name = "ErrMsg", required = true)
    protected String errMsg;
    @XmlElement(name = "Progress")
    protected Integer progress;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the cmd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmd() {
        return cmd;
    }

    /**
     * Sets the value of the cmd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmd(String value) {
        this.cmd = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the errCode property.
     * 
     */
    public int getErrCode() {
        return errCode;
    }

    /**
     * Sets the value of the errCode property.
     * 
     */
    public void setErrCode(int value) {
        this.errCode = value;
    }

    /**
     * Gets the value of the errMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * Sets the value of the errMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrMsg(String value) {
        this.errMsg = value;
    }

    /**
     * Gets the value of the progress property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProgress() {
        return progress;
    }

    /**
     * Sets the value of the progress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProgress(Integer value) {
        this.progress = value;
    }

}
