//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.21 at 12:23:44 AM GST 
//


package com.liconic.binding.sys;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for STXCassette complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STXCassette">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CassDevId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="CassType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="CassLevels" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="CassPltType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CassLvl" type="{}STXLevel" maxOccurs="unbounded"/>
 *         &lt;element name="CassSafe" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CassBuff" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STXCassette", propOrder = {
    "cassDevId",
    "cassType",
    "cassLevels",
    "cassPltType",
    "id",
    "cassLvl",
    "cassSafe",
    "cassBuff"
})
public class STXCassette {

    @XmlElement(name = "CassDevId", required = true)
    protected BigInteger cassDevId;
    @XmlElement(name = "CassType", required = true)
    protected BigInteger cassType;
    @XmlElement(name = "CassLevels", required = true)
    protected BigInteger cassLevels;
    @XmlElement(name = "CassPltType", required = true)
    protected BigInteger cassPltType;
    @XmlElement(name = "Id")
    protected int id;
    @XmlElement(name = "CassLvl", required = true)
    protected List<STXLevel> cassLvl;
    @XmlElement(name = "CassSafe")
    protected boolean cassSafe;
    @XmlElement(name = "CassBuff")
    protected boolean cassBuff;

    /**
     * Gets the value of the cassDevId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCassDevId() {
        return cassDevId;
    }

    /**
     * Sets the value of the cassDevId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCassDevId(BigInteger value) {
        this.cassDevId = value;
    }

    /**
     * Gets the value of the cassType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCassType() {
        return cassType;
    }

    /**
     * Sets the value of the cassType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCassType(BigInteger value) {
        this.cassType = value;
    }

    /**
     * Gets the value of the cassLevels property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCassLevels() {
        return cassLevels;
    }

    /**
     * Sets the value of the cassLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCassLevels(BigInteger value) {
        this.cassLevels = value;
    }

    /**
     * Gets the value of the cassPltType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCassPltType() {
        return cassPltType;
    }

    /**
     * Sets the value of the cassPltType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCassPltType(BigInteger value) {
        this.cassPltType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the cassLvl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cassLvl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCassLvl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STXLevel }
     * 
     * 
     */
    public List<STXLevel> getCassLvl() {
        if (cassLvl == null) {
            cassLvl = new ArrayList<STXLevel>();
        }
        return this.cassLvl;
    }

    /**
     * Gets the value of the cassSafe property.
     * 
     */
    public boolean isCassSafe() {
        return cassSafe;
    }

    /**
     * Sets the value of the cassSafe property.
     * 
     */
    public void setCassSafe(boolean value) {
        this.cassSafe = value;
    }

    /**
     * Gets the value of the cassBuff property.
     * 
     */
    public boolean isCassBuff() {
        return cassBuff;
    }

    /**
     * Sets the value of the cassBuff property.
     * 
     */
    public void setCassBuff(boolean value) {
        this.cassBuff = value;
    }

}
