//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.21 at 12:23:44 AM GST 
//


package com.liconic.binding.sys;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Keep the instance of device for commands: Activate, Deactivate, GetDeviceStatus and replyes for those commands.
 * 
 * <p>Java class for STXDevice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STXDevice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SystemReady" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PlateReady" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SystemInitialized" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="XferStnStatusChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="GateClosed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="UserDooreClosed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Warning" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PlateSensShovel" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PlateSensXferStn1" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PlateSensXferStn2" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Error" type="{}STXDeviceError" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STXDevice", propOrder = {
    "name",
    "systemReady",
    "plateReady",
    "systemInitialized",
    "xferStnStatusChange",
    "gateClosed",
    "userDooreClosed",
    "warning",
    "plateSensShovel",
    "plateSensXferStn1",
    "plateSensXferStn2",
    "error"
})
public class STXDevice {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "SystemReady")
    protected Boolean systemReady;
    @XmlElement(name = "PlateReady")
    protected Boolean plateReady;
    @XmlElement(name = "SystemInitialized")
    protected Boolean systemInitialized;
    @XmlElement(name = "XferStnStatusChange")
    protected Boolean xferStnStatusChange;
    @XmlElement(name = "GateClosed")
    protected Boolean gateClosed;
    @XmlElement(name = "UserDooreClosed")
    protected Boolean userDooreClosed;
    @XmlElement(name = "Warning")
    protected Boolean warning;
    @XmlElement(name = "PlateSensShovel")
    protected Boolean plateSensShovel;
    @XmlElement(name = "PlateSensXferStn1")
    protected Boolean plateSensXferStn1;
    @XmlElement(name = "PlateSensXferStn2")
    protected Boolean plateSensXferStn2;
    @XmlElement(name = "Error")
    protected STXDeviceError error;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the systemReady property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSystemReady() {
        return systemReady;
    }

    /**
     * Sets the value of the systemReady property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSystemReady(Boolean value) {
        this.systemReady = value;
    }

    /**
     * Gets the value of the plateReady property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlateReady() {
        return plateReady;
    }

    /**
     * Sets the value of the plateReady property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlateReady(Boolean value) {
        this.plateReady = value;
    }

    /**
     * Gets the value of the systemInitialized property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSystemInitialized() {
        return systemInitialized;
    }

    /**
     * Sets the value of the systemInitialized property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSystemInitialized(Boolean value) {
        this.systemInitialized = value;
    }

    /**
     * Gets the value of the xferStnStatusChange property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXferStnStatusChange() {
        return xferStnStatusChange;
    }

    /**
     * Sets the value of the xferStnStatusChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXferStnStatusChange(Boolean value) {
        this.xferStnStatusChange = value;
    }

    /**
     * Gets the value of the gateClosed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGateClosed() {
        return gateClosed;
    }

    /**
     * Sets the value of the gateClosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGateClosed(Boolean value) {
        this.gateClosed = value;
    }

    /**
     * Gets the value of the userDooreClosed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUserDooreClosed() {
        return userDooreClosed;
    }

    /**
     * Sets the value of the userDooreClosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserDooreClosed(Boolean value) {
        this.userDooreClosed = value;
    }

    /**
     * Gets the value of the warning property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWarning() {
        return warning;
    }

    /**
     * Sets the value of the warning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWarning(Boolean value) {
        this.warning = value;
    }

    /**
     * Gets the value of the plateSensShovel property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlateSensShovel() {
        return plateSensShovel;
    }

    /**
     * Sets the value of the plateSensShovel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlateSensShovel(Boolean value) {
        this.plateSensShovel = value;
    }

    /**
     * Gets the value of the plateSensXferStn1 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlateSensXferStn1() {
        return plateSensXferStn1;
    }

    /**
     * Sets the value of the plateSensXferStn1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlateSensXferStn1(Boolean value) {
        this.plateSensXferStn1 = value;
    }

    /**
     * Gets the value of the plateSensXferStn2 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlateSensXferStn2() {
        return plateSensXferStn2;
    }

    /**
     * Sets the value of the plateSensXferStn2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlateSensXferStn2(Boolean value) {
        this.plateSensXferStn2 = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link STXDeviceError }
     *     
     */
    public STXDeviceError getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link STXDeviceError }
     *     
     */
    public void setError(STXDeviceError value) {
        this.error = value;
    }

}
