//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.21 at 12:23:44 AM GST 
//


package com.liconic.binding.sys;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for STXLevel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STXLevel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LvlCassId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="LvlDevId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="LvlPlt" type="{}STXPlate" minOccurs="0"/>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="LvlInvDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="LvlLoadDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="LvlUnloadDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STXLevel", propOrder = {
    "lvlCassId",
    "lvlDevId",
    "lvlPlt",
    "id",
    "lvlInvDate",
    "lvlLoadDate",
    "lvlUnloadDate"
})
public class STXLevel {

    @XmlElement(name = "LvlCassId", required = true)
    protected BigInteger lvlCassId;
    @XmlElement(name = "LvlDevId", required = true)
    protected BigInteger lvlDevId;
    @XmlElementRef(name = "LvlPlt", type = JAXBElement.class)
    protected JAXBElement<STXPlate> lvlPlt;
    @XmlElement(name = "Id", required = true)
    protected BigInteger id;
    @XmlElementRef(name = "LvlInvDate", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> lvlInvDate;
    @XmlElementRef(name = "LvlLoadDate", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> lvlLoadDate;
    @XmlElement(name = "LvlUnloadDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lvlUnloadDate;

    /**
     * Gets the value of the lvlCassId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLvlCassId() {
        return lvlCassId;
    }

    /**
     * Sets the value of the lvlCassId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLvlCassId(BigInteger value) {
        this.lvlCassId = value;
    }

    /**
     * Gets the value of the lvlDevId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLvlDevId() {
        return lvlDevId;
    }

    /**
     * Sets the value of the lvlDevId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLvlDevId(BigInteger value) {
        this.lvlDevId = value;
    }

    /**
     * Gets the value of the lvlPlt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link STXPlate }{@code >}
     *     
     */
    public JAXBElement<STXPlate> getLvlPlt() {
        return lvlPlt;
    }

    /**
     * Sets the value of the lvlPlt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link STXPlate }{@code >}
     *     
     */
    public void setLvlPlt(JAXBElement<STXPlate> value) {
        this.lvlPlt = ((JAXBElement<STXPlate> ) value);
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the lvlInvDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getLvlInvDate() {
        return lvlInvDate;
    }

    /**
     * Sets the value of the lvlInvDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setLvlInvDate(JAXBElement<XMLGregorianCalendar> value) {
        this.lvlInvDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the lvlLoadDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getLvlLoadDate() {
        return lvlLoadDate;
    }

    /**
     * Sets the value of the lvlLoadDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setLvlLoadDate(JAXBElement<XMLGregorianCalendar> value) {
        this.lvlLoadDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the lvlUnloadDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLvlUnloadDate() {
        return lvlUnloadDate;
    }

    /**
     * Sets the value of the lvlUnloadDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLvlUnloadDate(XMLGregorianCalendar value) {
        this.lvlUnloadDate = value;
    }

}
