//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.21 at 12:23:44 AM GST 
//


package com.liconic.binding.sys;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for STXPlate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STXPlate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="PltBCR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PltUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PltMat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PltConc" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PltF" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PltTPos" type="{}STXTubePos" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PltType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="INFO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Location" type="{}STXPlateLocation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STXPlate", propOrder = {
    "id",
    "pltBCR",
    "pltUID",
    "pltMat",
    "pltConc",
    "pltF",
    "pltTPos",
    "pltType",
    "info",
    "location"
})
public class STXPlate {

    @XmlElement(name = "Id", required = true)
    protected BigInteger id;
    @XmlElement(name = "PltBCR", required = true)
    protected String pltBCR;
    @XmlElement(name = "PltUID", required = true)
    protected String pltUID;
    @XmlElement(name = "PltMat")
    protected String pltMat;
    @XmlElement(name = "PltConc")
    protected BigDecimal pltConc;
    @XmlElement(name = "PltF")
    protected BigDecimal pltF;
    @XmlElement(name = "PltTPos", nillable = true)
    protected List<STXTubePos> pltTPos;
    @XmlElement(name = "PltType")
    protected int pltType;
    @XmlElement(name = "INFO")
    protected String info;
    @XmlElement(name = "Location")
    protected STXPlateLocation location;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the pltBCR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPltBCR() {
        return pltBCR;
    }

    /**
     * Sets the value of the pltBCR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPltBCR(String value) {
        this.pltBCR = value;
    }

    /**
     * Gets the value of the pltUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPltUID() {
        return pltUID;
    }

    /**
     * Sets the value of the pltUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPltUID(String value) {
        this.pltUID = value;
    }

    /**
     * Gets the value of the pltMat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPltMat() {
        return pltMat;
    }

    /**
     * Sets the value of the pltMat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPltMat(String value) {
        this.pltMat = value;
    }

    /**
     * Gets the value of the pltConc property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPltConc() {
        return pltConc;
    }

    /**
     * Sets the value of the pltConc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPltConc(BigDecimal value) {
        this.pltConc = value;
    }

    /**
     * Gets the value of the pltF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPltF() {
        return pltF;
    }

    /**
     * Sets the value of the pltF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPltF(BigDecimal value) {
        this.pltF = value;
    }

    /**
     * Gets the value of the pltTPos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pltTPos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPltTPos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STXTubePos }
     * 
     * 
     */
    public List<STXTubePos> getPltTPos() {
        if (pltTPos == null) {
            pltTPos = new ArrayList<STXTubePos>();
        }
        return this.pltTPos;
    }

    /**
     * Gets the value of the pltType property.
     * 
     */
    public int getPltType() {
        return pltType;
    }

    /**
     * Sets the value of the pltType property.
     * 
     */
    public void setPltType(int value) {
        this.pltType = value;
    }

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINFO() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINFO(String value) {
        this.info = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link STXPlateLocation }
     *     
     */
    public STXPlateLocation getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link STXPlateLocation }
     *     
     */
    public void setLocation(STXPlateLocation value) {
        this.location = value;
    }

}
