//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.21 at 12:23:44 AM GST 
//


package com.liconic.binding.sys;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for STXPlateLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STXPlateLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PLType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Partition"/>
 *               &lt;enumeration value="Transferstation"/>
 *               &lt;enumeration value="Picker"/>
 *               &lt;enumeration value="Handler"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PLName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STXPlateLocation", propOrder = {
    "plType",
    "plName"
})
public class STXPlateLocation {

    @XmlElement(name = "PLType", required = true)
    protected String plType;
    @XmlElement(name = "PLName", required = true)
    protected String plName;

    /**
     * Gets the value of the plType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPLType() {
        return plType;
    }

    /**
     * Sets the value of the plType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPLType(String value) {
        this.plType = value;
    }

    /**
     * Gets the value of the plName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPLName() {
        return plName;
    }

    /**
     * Sets the value of the plName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPLName(String value) {
        this.plName = value;
    }

}
