//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.21 at 12:23:44 AM GST 
//


package com.liconic.binding.sys;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for STXTube complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STXTube">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="TbBCR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TbUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TbM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TbC" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TbF" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TbT" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="INFO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MainGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STXTube", propOrder = {
    "id",
    "tbBCR",
    "tbUID",
    "tbM",
    "tbC",
    "tbF",
    "tbT",
    "info",
    "subGroup",
    "mainGroup"
})
public class STXTube {

    @XmlElement(name = "Id", required = true)
    protected BigInteger id;
    @XmlElement(name = "TbBCR", required = true)
    protected String tbBCR;
    @XmlElement(name = "TbUID", required = true)
    protected String tbUID;
    @XmlElement(name = "TbM", required = true)
    protected String tbM;
    @XmlElement(name = "TbC", required = true)
    protected BigDecimal tbC;
    @XmlElement(name = "TbF", required = true)
    protected BigDecimal tbF;
    @XmlElement(name = "TbT")
    protected int tbT;
    @XmlElement(name = "INFO", required = true)
    protected String info;
    @XmlElement(name = "SubGroup")
    protected String subGroup;
    @XmlElement(name = "MainGroup")
    protected String mainGroup;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the tbBCR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTbBCR() {
        return tbBCR;
    }

    /**
     * Sets the value of the tbBCR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTbBCR(String value) {
        this.tbBCR = value;
    }

    /**
     * Gets the value of the tbUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTbUID() {
        return tbUID;
    }

    /**
     * Sets the value of the tbUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTbUID(String value) {
        this.tbUID = value;
    }

    /**
     * Gets the value of the tbM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTbM() {
        return tbM;
    }

    /**
     * Sets the value of the tbM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTbM(String value) {
        this.tbM = value;
    }

    /**
     * Gets the value of the tbC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTbC() {
        return tbC;
    }

    /**
     * Sets the value of the tbC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTbC(BigDecimal value) {
        this.tbC = value;
    }

    /**
     * Gets the value of the tbF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTbF() {
        return tbF;
    }

    /**
     * Sets the value of the tbF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTbF(BigDecimal value) {
        this.tbF = value;
    }

    /**
     * Gets the value of the tbT property.
     * 
     */
    public int getTbT() {
        return tbT;
    }

    /**
     * Sets the value of the tbT property.
     * 
     */
    public void setTbT(int value) {
        this.tbT = value;
    }

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINFO() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINFO(String value) {
        this.info = value;
    }

    /**
     * Gets the value of the subGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubGroup() {
        return subGroup;
    }

    /**
     * Sets the value of the subGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubGroup(String value) {
        this.subGroup = value;
    }

    /**
     * Gets the value of the mainGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainGroup() {
        return mainGroup;
    }

    /**
     * Sets the value of the mainGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainGroup(String value) {
        this.mainGroup = value;
    }

}
