//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.21 at 12:23:44 AM GST 
//
package com.liconic.binding.stx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Command" type="{}STXCommand"/>
 *         &lt;element name="Answer" type="{}STXAnswer" minOccurs="0"/>
 *         &lt;element name="Plates" type="{}STXPlate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Tubes" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Tube" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Plate" type="{}STXPlate" minOccurs="0"/>
 *                   &lt;element name="PltTPos" type="{}STXTubePos" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="STXInfo" type="{}STXUnit" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PendingCommand" type="{}STXCmdStatus" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Device" type="{}STXDevice" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "command",
    "answer",
    "plates",
    "tubes",
    "stxInfo",
    "pendingCommand",
    "device"
})
@XmlRootElement(name = "STXRequest")
public class STXRequest {

    @XmlElement(name = "Command", required = true)
    protected STXCommand command;
    @XmlElement(name = "Answer")
    protected STXAnswer answer;
    @XmlElement(name = "Plates")
    protected List<STXPlate> plates;
    @XmlElement(name = "Tubes")
    protected List<STXRequest.Tubes> tubes;
    @XmlElement(name = "STXInfo")
    protected List<STXUnit> stxInfo;
    @XmlElement(name = "PendingCommand")
    protected List<STXCmdStatus> pendingCommand;
    @XmlElement(name = "Device")
    protected STXDevice device;

    /**
     * Gets the value of the command property.
     *
     * @return possible object is {@link STXCommand }
     *
     */
    public STXCommand getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     *
     * @param value allowed object is {@link STXCommand }
     *
     */
    public void setCommand(STXCommand value) {
        this.command = value;
    }

    /**
     * Gets the value of the answer property.
     *
     * @return possible object is {@link STXAnswer }
     *
     */
    public STXAnswer getAnswer() {
        return answer;
    }

    /**
     * Sets the value of the answer property.
     *
     * @param value allowed object is {@link STXAnswer }
     *
     */
    public void setAnswer(STXAnswer value) {
        this.answer = value;
    }

    /**
     * Gets the value of the plates property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the plates property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlates().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STXPlate }
     *
     *
     */
    public List<STXPlate> getPlates() {
        if (plates == null) {
            plates = new ArrayList<STXPlate>();
        }
        return this.plates;
    }

    /**
     * Gets the value of the tubes property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the tubes property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTubes().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STXRequest.Tubes }
     *
     *
     */
    public List<STXRequest.Tubes> getTubes() {
        if (tubes == null) {
            tubes = new ArrayList<STXRequest.Tubes>();
        }
        return this.tubes;
    }

    /**
     * Gets the value of the stxInfo property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the stxInfo property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTXInfo().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link STXUnit }
     *
     *
     */
    public List<STXUnit> getSTXInfo() {
        if (stxInfo == null) {
            stxInfo = new ArrayList<STXUnit>();
        }
        return this.stxInfo;
    }

    /**
     * Gets the value of the pendingCommand property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the pendingCommand property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPendingCommand().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STXCmdStatus }
     *
     *
     */
    public List<STXCmdStatus> getPendingCommand() {
        if (pendingCommand == null) {
            pendingCommand = new ArrayList<STXCmdStatus>();
        }
        return this.pendingCommand;
    }

    /**
     * Gets the value of the device property.
     *
     * @return possible object is {@link STXDevice }
     *
     */
    public STXDevice getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     *
     * @param value allowed object is {@link STXDevice }
     *
     */
    public void setDevice(STXDevice value) {
        this.device = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Tube" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Plate" type="{}STXPlate" minOccurs="0"/>
     *         &lt;element name="PltTPos" type="{}STXTubePos" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tube",
        "plate",
        "pltTPos"
    })
    public static class Tubes {

        @XmlElement(name = "Tube", required = true)
        protected String tube;
        @XmlElement(name = "Plate")
        protected STXPlate plate;
        @XmlElement(name = "PltTPos")
        protected STXTubePos pltTPos;

        /**
         * Gets the value of the tube property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getTube() {
            return tube;
        }

        /**
         * Sets the value of the tube property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setTube(String value) {
            this.tube = value;
        }

        /**
         * Gets the value of the plate property.
         *
         * @return possible object is {@link STXPlate }
         *
         */
        public STXPlate getPlate() {
            return plate;
        }

        /**
         * Sets the value of the plate property.
         *
         * @param value allowed object is {@link STXPlate }
         *
         */
        public void setPlate(STXPlate value) {
            this.plate = value;
        }

        /**
         * Gets the value of the pltTPos property.
         *
         * @return possible object is {@link STXTubePos }
         *
         */
        public STXTubePos getPltTPos() {
            return pltTPos;
        }

        /**
         * Sets the value of the pltTPos property.
         *
         * @param value allowed object is {@link STXTubePos }
         *
         */
        public void setPltTPos(STXTubePos value) {
            this.pltTPos = value;
        }

    }

}
