//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.21 at 12:23:44 AM GST 
//
package com.liconic.binding.stx;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for STXTubePos complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="STXTubePos">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="PX" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="PY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="PYA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PTV" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="PTb" type="{}STXTube" minOccurs="0"/>
 *         &lt;element name="PIDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="PLDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="PUDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Info" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STXTubePos", propOrder = {
    "id",
    "px",
    "py",
    "pya",
    "ptv",
    "pTb",
    "piDt",
    "plDt",
    "puDt",
    "info"
})
public class STXTubePos {

    @XmlElement(name = "Id", required = true)
    protected BigInteger id;
    @XmlElement(name = "PX")
    protected byte px;
    @XmlElement(name = "PY")
    protected byte py;
    @XmlElement(name = "PYA")
    protected String pya;
    @XmlElement(name = "PTV", required = true)
    protected BigInteger ptv;
    @XmlElementRef(name = "PTb", type = JAXBElement.class)
    protected JAXBElement<STXTube> pTb;
    @XmlElementRef(name = "PIDt", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> piDt;
    @XmlElementRef(name = "PLDt", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> plDt;
    @XmlElementRef(name = "PUDt", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> puDt;
    @XmlElementRef(name = "Info", type = JAXBElement.class)
    protected JAXBElement<String> info;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the px property.
     *
     */
    public byte getPX() {
        return px;
    }

    /**
     * Sets the value of the px property.
     *
     */
    public void setPX(byte value) {
        this.px = value;
    }

    /**
     * Gets the value of the py property.
     *
     */
    public byte getPY() {
        return py;
    }

    /**
     * Sets the value of the py property.
     *
     */
    public void setPY(byte value) {
        this.py = value;
    }

    /**
     * Gets the value of the pya property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPYA() {
        return pya;
    }

    /**
     * Sets the value of the pya property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPYA(String value) {
        this.pya = value;
    }

    /**
     * Gets the value of the ptv property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getPTV() {
        return ptv;
    }

    /**
     * Sets the value of the ptv property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setPTV(BigInteger value) {
        this.ptv = value;
    }

    /**
     * Gets the value of the pTb property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link STXTube }{@code >}
     *
     */
    public JAXBElement<STXTube> getPTb() {
        return pTb;
    }

    /**
     * Sets the value of the pTb property.
     *
     * @param value allowed object is
     * {@link JAXBElement }{@code <}{@link STXTube }{@code >}
     *
     */
    public void setPTb(JAXBElement<STXTube> value) {
        this.pTb = ((JAXBElement<STXTube>) value);
    }

    /**
     * Gets the value of the piDt property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *
     */
    public JAXBElement<XMLGregorianCalendar> getPIDt() {
        return piDt;
    }

    /**
     * Sets the value of the piDt property.
     *
     * @param value allowed object is
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *
     */
    public void setPIDt(JAXBElement<XMLGregorianCalendar> value) {
        this.piDt = ((JAXBElement<XMLGregorianCalendar>) value);
    }

    /**
     * Gets the value of the plDt property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *
     */
    public JAXBElement<XMLGregorianCalendar> getPLDt() {
        return plDt;
    }

    /**
     * Sets the value of the plDt property.
     *
     * @param value allowed object is
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *
     */
    public void setPLDt(JAXBElement<XMLGregorianCalendar> value) {
        this.plDt = ((JAXBElement<XMLGregorianCalendar>) value);
    }

    /**
     * Gets the value of the puDt property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *
     */
    public JAXBElement<XMLGregorianCalendar> getPUDt() {
        return puDt;
    }

    /**
     * Sets the value of the puDt property.
     *
     * @param value allowed object is
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *
     */
    public void setPUDt(JAXBElement<XMLGregorianCalendar> value) {
        this.puDt = ((JAXBElement<XMLGregorianCalendar>) value);
    }

    /**
     * Gets the value of the info property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    public JAXBElement<String> getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     *
     * @param value allowed object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    public void setInfo(JAXBElement<String> value) {
        this.info = ((JAXBElement<String>) value);
    }

}
