//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.21 at 12:23:44 AM GST 
//
package com.liconic.binding.stx;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for STXUnit complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="STXUnit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UnitFW" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UnitSN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UnitDoubleDeck" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitActivated" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitError" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitBCR" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitPPSensor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitPShovelSensor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitPXfer1Sensor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitPXfer2Sensor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitCOMPort" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="UnitBCRCOMPort" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="UnitBCRInit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitReady" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitDoorOpened" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitErrorCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="UnitPlates" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="UnitCO2" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitO2" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitN2" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitTemperature" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitHumidity" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitDoors" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="UnitIO" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitCassette" type="{}STXCassette" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UnitPartition" type="{}STXPartition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UnitTransferStation" type="{}STXTransferStation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UnitOwner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnitSTT" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitSTTType" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="UnitSTTPos" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="UnitStorage" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STXUnit", propOrder = {
    "id",
    "name",
    "unitFW",
    "unitSN",
    "unitDoubleDeck",
    "unitActivated",
    "unitError",
    "unitBCR",
    "unitPPSensor",
    "unitPShovelSensor",
    "unitPXfer1Sensor",
    "unitPXfer2Sensor",
    "unitCOMPort",
    "unitBCRCOMPort",
    "unitBCRInit",
    "unitReady",
    "unitDoorOpened",
    "unitErrorCode",
    "unitPlates",
    "unitCO2",
    "unitO2",
    "unitN2",
    "unitTemperature",
    "unitHumidity",
    "unitDoors",
    "unitIO",
    "unitCassette",
    "unitPartition",
    "unitTransferStation",
    "unitOwner",
    "unitSTT",
    "unitSTTType",
    "unitSTTPos",
    "unitStorage"
})
public class STXUnit {

    @XmlElement(name = "Id")
    protected int id;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "UnitFW", required = true)
    protected String unitFW;
    @XmlElement(name = "UnitSN", required = true)
    protected String unitSN;
    @XmlElement(name = "UnitDoubleDeck")
    protected boolean unitDoubleDeck;
    @XmlElement(name = "UnitActivated")
    protected boolean unitActivated;
    @XmlElement(name = "UnitError")
    protected boolean unitError;
    @XmlElement(name = "UnitBCR")
    protected boolean unitBCR;
    @XmlElement(name = "UnitPPSensor")
    protected boolean unitPPSensor;
    @XmlElement(name = "UnitPShovelSensor")
    protected boolean unitPShovelSensor;
    @XmlElement(name = "UnitPXfer1Sensor")
    protected boolean unitPXfer1Sensor;
    @XmlElement(name = "UnitPXfer2Sensor")
    protected boolean unitPXfer2Sensor;
    @XmlElement(name = "UnitCOMPort", required = true)
    protected BigInteger unitCOMPort;
    @XmlElement(name = "UnitBCRCOMPort", required = true)
    protected BigInteger unitBCRCOMPort;
    @XmlElement(name = "UnitBCRInit")
    protected boolean unitBCRInit;
    @XmlElement(name = "UnitReady")
    protected boolean unitReady;
    @XmlElement(name = "UnitDoorOpened")
    protected boolean unitDoorOpened;
    @XmlElement(name = "UnitErrorCode", required = true)
    protected BigInteger unitErrorCode;
    @XmlElement(name = "UnitPlates", required = true)
    protected BigInteger unitPlates;
    @XmlElement(name = "UnitCO2")
    protected boolean unitCO2;
    @XmlElement(name = "UnitO2")
    protected boolean unitO2;
    @XmlElement(name = "UnitN2")
    protected boolean unitN2;
    @XmlElement(name = "UnitTemperature")
    protected boolean unitTemperature;
    @XmlElement(name = "UnitHumidity")
    protected boolean unitHumidity;
    @XmlElement(name = "UnitDoors", required = true)
    protected BigInteger unitDoors;
    @XmlElement(name = "UnitIO")
    protected boolean unitIO;
    @XmlElement(name = "UnitCassette")
    protected List<STXCassette> unitCassette;
    @XmlElement(name = "UnitPartition", nillable = true)
    protected List<STXPartition> unitPartition;
    @XmlElement(name = "UnitTransferStation", nillable = true)
    protected List<STXTransferStation> unitTransferStation;
    @XmlElement(name = "UnitOwner")
    protected String unitOwner;
    @XmlElement(name = "UnitSTT")
    protected boolean unitSTT;
    @XmlElement(name = "UnitSTTType")
    protected Integer unitSTTType;
    @XmlElement(name = "UnitSTTPos")
    protected Integer unitSTTPos;
    @XmlElement(name = "UnitStorage")
    protected boolean unitStorage;

    /**
     * Gets the value of the id property.
     *
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the unitFW property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUnitFW() {
        return unitFW;
    }

    /**
     * Sets the value of the unitFW property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUnitFW(String value) {
        this.unitFW = value;
    }

    /**
     * Gets the value of the unitSN property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUnitSN() {
        return unitSN;
    }

    /**
     * Sets the value of the unitSN property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUnitSN(String value) {
        this.unitSN = value;
    }

    /**
     * Gets the value of the unitDoubleDeck property.
     *
     */
    public boolean isUnitDoubleDeck() {
        return unitDoubleDeck;
    }

    /**
     * Sets the value of the unitDoubleDeck property.
     *
     */
    public void setUnitDoubleDeck(boolean value) {
        this.unitDoubleDeck = value;
    }

    /**
     * Gets the value of the unitActivated property.
     *
     */
    public boolean isUnitActivated() {
        return unitActivated;
    }

    /**
     * Sets the value of the unitActivated property.
     *
     */
    public void setUnitActivated(boolean value) {
        this.unitActivated = value;
    }

    /**
     * Gets the value of the unitError property.
     *
     */
    public boolean isUnitError() {
        return unitError;
    }

    /**
     * Sets the value of the unitError property.
     *
     */
    public void setUnitError(boolean value) {
        this.unitError = value;
    }

    /**
     * Gets the value of the unitBCR property.
     *
     */
    public boolean isUnitBCR() {
        return unitBCR;
    }

    /**
     * Sets the value of the unitBCR property.
     *
     */
    public void setUnitBCR(boolean value) {
        this.unitBCR = value;
    }

    /**
     * Gets the value of the unitPPSensor property.
     *
     */
    public boolean isUnitPPSensor() {
        return unitPPSensor;
    }

    /**
     * Sets the value of the unitPPSensor property.
     *
     */
    public void setUnitPPSensor(boolean value) {
        this.unitPPSensor = value;
    }

    /**
     * Gets the value of the unitPShovelSensor property.
     *
     */
    public boolean isUnitPShovelSensor() {
        return unitPShovelSensor;
    }

    /**
     * Sets the value of the unitPShovelSensor property.
     *
     */
    public void setUnitPShovelSensor(boolean value) {
        this.unitPShovelSensor = value;
    }

    /**
     * Gets the value of the unitPXfer1Sensor property.
     *
     */
    public boolean isUnitPXfer1Sensor() {
        return unitPXfer1Sensor;
    }

    /**
     * Sets the value of the unitPXfer1Sensor property.
     *
     */
    public void setUnitPXfer1Sensor(boolean value) {
        this.unitPXfer1Sensor = value;
    }

    /**
     * Gets the value of the unitPXfer2Sensor property.
     *
     */
    public boolean isUnitPXfer2Sensor() {
        return unitPXfer2Sensor;
    }

    /**
     * Sets the value of the unitPXfer2Sensor property.
     *
     */
    public void setUnitPXfer2Sensor(boolean value) {
        this.unitPXfer2Sensor = value;
    }

    /**
     * Gets the value of the unitCOMPort property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getUnitCOMPort() {
        return unitCOMPort;
    }

    /**
     * Sets the value of the unitCOMPort property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setUnitCOMPort(BigInteger value) {
        this.unitCOMPort = value;
    }

    /**
     * Gets the value of the unitBCRCOMPort property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getUnitBCRCOMPort() {
        return unitBCRCOMPort;
    }

    /**
     * Sets the value of the unitBCRCOMPort property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setUnitBCRCOMPort(BigInteger value) {
        this.unitBCRCOMPort = value;
    }

    /**
     * Gets the value of the unitBCRInit property.
     *
     */
    public boolean isUnitBCRInit() {
        return unitBCRInit;
    }

    /**
     * Sets the value of the unitBCRInit property.
     *
     */
    public void setUnitBCRInit(boolean value) {
        this.unitBCRInit = value;
    }

    /**
     * Gets the value of the unitReady property.
     *
     */
    public boolean isUnitReady() {
        return unitReady;
    }

    /**
     * Sets the value of the unitReady property.
     *
     */
    public void setUnitReady(boolean value) {
        this.unitReady = value;
    }

    /**
     * Gets the value of the unitDoorOpened property.
     *
     */
    public boolean isUnitDoorOpened() {
        return unitDoorOpened;
    }

    /**
     * Sets the value of the unitDoorOpened property.
     *
     */
    public void setUnitDoorOpened(boolean value) {
        this.unitDoorOpened = value;
    }

    /**
     * Gets the value of the unitErrorCode property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getUnitErrorCode() {
        return unitErrorCode;
    }

    /**
     * Sets the value of the unitErrorCode property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setUnitErrorCode(BigInteger value) {
        this.unitErrorCode = value;
    }

    /**
     * Gets the value of the unitPlates property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getUnitPlates() {
        return unitPlates;
    }

    /**
     * Sets the value of the unitPlates property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setUnitPlates(BigInteger value) {
        this.unitPlates = value;
    }

    /**
     * Gets the value of the unitCO2 property.
     *
     */
    public boolean isUnitCO2() {
        return unitCO2;
    }

    /**
     * Sets the value of the unitCO2 property.
     *
     */
    public void setUnitCO2(boolean value) {
        this.unitCO2 = value;
    }

    /**
     * Gets the value of the unitO2 property.
     *
     */
    public boolean isUnitO2() {
        return unitO2;
    }

    /**
     * Sets the value of the unitO2 property.
     *
     */
    public void setUnitO2(boolean value) {
        this.unitO2 = value;
    }

    /**
     * Gets the value of the unitN2 property.
     *
     */
    public boolean isUnitN2() {
        return unitN2;
    }

    /**
     * Sets the value of the unitN2 property.
     *
     */
    public void setUnitN2(boolean value) {
        this.unitN2 = value;
    }

    /**
     * Gets the value of the unitTemperature property.
     *
     */
    public boolean isUnitTemperature() {
        return unitTemperature;
    }

    /**
     * Sets the value of the unitTemperature property.
     *
     */
    public void setUnitTemperature(boolean value) {
        this.unitTemperature = value;
    }

    /**
     * Gets the value of the unitHumidity property.
     *
     */
    public boolean isUnitHumidity() {
        return unitHumidity;
    }

    /**
     * Sets the value of the unitHumidity property.
     *
     */
    public void setUnitHumidity(boolean value) {
        this.unitHumidity = value;
    }

    /**
     * Gets the value of the unitDoors property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getUnitDoors() {
        return unitDoors;
    }

    /**
     * Sets the value of the unitDoors property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setUnitDoors(BigInteger value) {
        this.unitDoors = value;
    }

    /**
     * Gets the value of the unitIO property.
     *
     */
    public boolean isUnitIO() {
        return unitIO;
    }

    /**
     * Sets the value of the unitIO property.
     *
     */
    public void setUnitIO(boolean value) {
        this.unitIO = value;
    }

    /**
     * Gets the value of the unitCassette property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the unitCassette property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnitCassette().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STXCassette }
     *
     *
     */
    public List<STXCassette> getUnitCassette() {
        if (unitCassette == null) {
            unitCassette = new ArrayList<STXCassette>();
        }
        return this.unitCassette;
    }

    /**
     * Gets the value of the unitPartition property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the unitPartition property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnitPartition().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STXPartition }
     *
     *
     */
    public List<STXPartition> getUnitPartition() {
        if (unitPartition == null) {
            unitPartition = new ArrayList<STXPartition>();
        }
        return this.unitPartition;
    }

    /**
     * Gets the value of the unitTransferStation property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the unitTransferStation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnitTransferStation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STXTransferStation }
     *
     *
     */
    public List<STXTransferStation> getUnitTransferStation() {
        if (unitTransferStation == null) {
            unitTransferStation = new ArrayList<STXTransferStation>();
        }
        return this.unitTransferStation;
    }

    /**
     * Gets the value of the unitOwner property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUnitOwner() {
        return unitOwner;
    }

    /**
     * Sets the value of the unitOwner property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUnitOwner(String value) {
        this.unitOwner = value;
    }

    /**
     * Gets the value of the unitSTT property.
     *
     */
    public boolean isUnitSTT() {
        return unitSTT;
    }

    /**
     * Sets the value of the unitSTT property.
     *
     */
    public void setUnitSTT(boolean value) {
        this.unitSTT = value;
    }

    /**
     * Gets the value of the unitSTTType property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getUnitSTTType() {
        return unitSTTType;
    }

    /**
     * Sets the value of the unitSTTType property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setUnitSTTType(Integer value) {
        this.unitSTTType = value;
    }

    /**
     * Gets the value of the unitSTTPos property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getUnitSTTPos() {
        return unitSTTPos;
    }

    /**
     * Sets the value of the unitSTTPos property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setUnitSTTPos(Integer value) {
        this.unitSTTPos = value;
    }

    /**
     * Gets the value of the unitStorage property.
     *
     */
    public boolean isUnitStorage() {
        return unitStorage;
    }

    /**
     * Sets the value of the unitStorage property.
     *
     */
    public void setUnitStorage(boolean value) {
        this.unitStorage = value;
    }

}
